ENH Update reference to supported modules data
silverstripe/silverstripe-tx-translator pull request #29
Opened 2024-05-08 03:27 UTC by GuySartorelli

## Issues
- https://github.com/silverstripe/.github/issues/237

2024-05-08 03:53 UTC, GuySartorelli commented on composer.json
> +        "php": "^8.1",
supported-modules needs 8.1

2024-05-08 22:19 UTC, emteknetnz requested changes

2024-05-08 22:19 UTC, emteknetnz commented on .github/workflows/ci.yml
> -  schedule:
We should keep the schedule? If an auto-tag fails on merge (happens very occasionally) the cron will pick it up

2024-05-08 22:20 UTC, GuySartorelli commented on .github/workflows/ci.yml
> -  schedule:
Standardiser will add dispatch-ci to this module when it's next run. This is the way we do this for all repos that use standard CI.

2024-05-09 01:50 UTC, emteknetnz approved these changes

2024-05-09 01:51 UTC, merged

2024-05-09 01:51 UTC, emteknetnz commented
Have released [1.2.0](https://github.com/silverstripe/silverstripe-tx-translator/releases/tag/1.2.0)